# Generated by Django 3.1.7 on 2021-04-02 17:19

from django.db import migrations, models
import publications.validators


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='reg_number',
            field=models.CharField(max_length=12, validators=[publications.validators.RegNumberValidator()]),
        ),
    ]
